# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '2.0.2.dev25+gfd52994.d20230721'
__version_tuple__ = version_tuple = (2, 0, 2, 'dev25', 'gfd52994.d20230721')
