name: pre-merge Python3.10 CI

on:
  push:
    branches:
      - enhancement/docs/versioned_docs

env:
  QSPPRED_TEST_EXTRAS: false
  QSPPRED_PYTEST_ARGS: "--junitxml=test_report.xml"

jobs:
  ubuntu_python_3_10:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    defaults:
      run:
        shell: bash
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set Up Dependencies
        run: |
          source .github/setup.sh

      - name: Run pytest
        run: cd testing/test_pytest && ./run.sh

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'testing/test_pytest/test_report.xml'

      - name: Test CLI
        run: cd testing/test_cli && ./run.sh

      - name: Test Consistency
        run: cd testing/test_consistency && ./run.sh